name: E-learning backend pipeline

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Download sources
        uses: actions/checkout@v4
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          java-version: '1.8'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean install --% -Dmaven.test.skip=true -B package --file pom.xml